development:
  adapter: postgresql
  encoding: unicode
  database: bePrepared_dev
  pool: 5
  username: user
  password: bePrepared1


  test:
  adapter: postgresql
  encoding: unicode
  database: bePrepared
  pool: 5
  username: user
  password: bePrepared1